// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModel(arg1) {
  return window['go']['main']['App']['CreateModel'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function RelayBaseURL() {
  return window['go']['main']['App']['RelayBaseURL']();
}

export function TokenStats(arg1) {
  return window['go']['main']['App']['TokenStats'](arg1);
}

export function UpdateModel(arg1) {
  return window['go']['main']['App']['UpdateModel'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}
