// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ListProviders():Promise<any[]>;

export function CreateProvider(arg1:any):Promise<any>;

export function UpdateProvider(arg1:any):Promise<any>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ListModels(arg1:string):Promise<any[]>;

export function CreateModel(arg1:any):Promise<any>;

export function UpdateModel(arg1:any):Promise<any>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;
