// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CallLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallLogs'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateAPIKey(arg1) {
  return window['go']['main']['App']['CreateAPIKey'](arg1);
}

export function CreateModel(arg1) {
  return window['go']['main']['App']['CreateModel'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function DeleteAPIKey(arg1) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DesktopSettings() {
  return window['go']['main']['App']['DesktopSettings']();
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['App']['FetchProviderModels'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideToTray(arg1) {
  return window['go']['main']['App']['HideToTray'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function ListAPIKeys() {
  return window['go']['main']['App']['ListAPIKeys']();
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListProviderPresets() {
  return window['go']['main']['App']['ListProviderPresets']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function LocalAccessAddresses() {
  return window['go']['main']['App']['LocalAccessAddresses']();
}

export function RelayBaseURL() {
  return window['go']['main']['App']['RelayBaseURL']();
}

export function RelayPort() {
  return window['go']['main']['App']['RelayPort']();
}

export function RelayServiceEnabled() {
  return window['go']['main']['App']['RelayServiceEnabled']();
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function SetHideOnClose(arg1) {
  return window['go']['main']['App']['SetHideOnClose'](arg1);
}

export function SetHideOnMinimize(arg1) {
  return window['go']['main']['App']['SetHideOnMinimize'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetRelayPort(arg1) {
  return window['go']['main']['App']['SetRelayPort'](arg1);
}

export function SetRelayServiceEnabled(arg1) {
  return window['go']['main']['App']['SetRelayServiceEnabled'](arg1);
}

export function SetStartMinimized(arg1) {
  return window['go']['main']['App']['SetStartMinimized'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function TestProviderModel(arg1, arg2) {
  return window['go']['main']['App']['TestProviderModel'](arg1, arg2);
}

export function TokenStatApps(arg1) {
  return window['go']['main']['App']['TokenStatApps'](arg1);
}

export function TokenStatModels(arg1) {
  return window['go']['main']['App']['TokenStatModels'](arg1);
}

export function TokenStatRows(arg1, arg2) {
  return window['go']['main']['App']['TokenStatRows'](arg1, arg2);
}

export function TokenStats(arg1) {
  return window['go']['main']['App']['TokenStats'](arg1);
}

export function TokenTrend(arg1, arg2, arg3) {
  return window['go']['main']['App']['TokenTrend'](arg1, arg2, arg3);
}

export function UpdateAPIKey(arg1) {
  return window['go']['main']['App']['UpdateAPIKey'](arg1);
}

export function UpdateModel(arg1) {
  return window['go']['main']['App']['UpdateModel'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}
