// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function CallLogs(arg1:store.TokenStatsFilter,arg2:number,arg3:number):Promise<store.CallLogPage>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CreateAPIKey(arg1:store.APIKeyInput):Promise<store.APIKey>;

export function CreateModel(arg1:store.ModelInput):Promise<store.Model>;

export function CreateProvider(arg1:store.ProviderInput):Promise<store.Provider>;

export function DeleteAPIKey(arg1:number):Promise<void>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function FetchProviderModels(arg1:string):Promise<Array<main.ProviderModel>>;

export function Greet(arg1:string):Promise<string>;

export function InstallUpdate(arg1:string):Promise<void>;

export function ListAPIKeys():Promise<Array<store.APIKey>>;

export function ListModels(arg1:string):Promise<Array<store.Model>>;

export function ListProviderPresets():Promise<Array<store.ProviderPreset>>;

export function ListProviders():Promise<Array<store.Provider>>;

export function RelayBaseURL():Promise<string>;

export function RelayPort():Promise<number>;

export function SetRelayPort(arg1:number):Promise<number>;

export function TestProviderModel(arg1:string,arg2:string):Promise<main.ProviderTestResult>;

export function TokenStatApps(arg1:store.TokenStatsFilter):Promise<Array<string>>;

export function TokenStatModels(arg1:store.TokenStatsFilter):Promise<Array<string>>;

export function TokenStatRows(arg1:store.TokenStatsFilter,arg2:string):Promise<Array<store.TokenStatRow>>;

export function TokenStats(arg1:store.TokenStatsFilter):Promise<store.TokenStats>;

export function TokenTrend(arg1:store.TokenStatsFilter,arg2:string,arg3:string):Promise<Array<store.TokenTrendPoint>>;

export function UpdateAPIKey(arg1:store.APIKeyInput):Promise<store.APIKey>;

export function UpdateModel(arg1:store.ModelInput):Promise<store.Model>;

export function UpdateProvider(arg1:store.ProviderInput):Promise<store.Provider>;
