// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function CreateModel(arg1:store.ModelInput):Promise<store.Model>;

export function CreateProvider(arg1:store.ProviderInput):Promise<store.Provider>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListModels(arg1:string):Promise<Array<store.Model>>;

export function ListProviders():Promise<Array<store.Provider>>;

export function RelayBaseURL():Promise<string>;

export function TokenStats(arg1:store.TokenStatsFilter):Promise<store.TokenStats>;

export function UpdateModel(arg1:store.ModelInput):Promise<store.Model>;

export function UpdateProvider(arg1:store.ProviderInput):Promise<store.Provider>;
